builds:
- binary: kubeswitch
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X "github.com/ckt114/kubeswitch/cmd.Version=v{{.Version}}"
release:
  prerelease: auto
universal_binaries:
  - replace: true
brews:
- name: kubeswitch
  homepage: "https://github.com/ckt114/kubeswitch"
  repository:
    owner: ckt114
    name: homebrew-taps
    branch: master
  commit_author:
    name: ckt114
    email: chung.k.tran@gmail.com
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

