builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X "github.com/ckt114/kubeswitch/cmd.Version=v{{.Version}}"
brews:
- homepage: "https://github.com/ckt114/kubeswitch"
  description: "Kubernetes context and namespace switching with style."
  license: "Apache-2.0"
  repository:
    owner: ckt114
    name: homebrew-tap
    branch: master
  commit_author:
    name: ckt114
    email: chung.k.tran@gmail.com
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

