name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.6'
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.23.0
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.DEFAULT_TOKEN }}

