name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: ${{ env.GITHUB_REF_NAME }}
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.DEFAULT_TOKEN }}
